import { AddProduct } from "../definitions/AddProduct";
import { AddProductResponse } from "../definitions/AddProductResponse";
import { SaveOffer } from "../definitions/SaveOffer";
import { SaveOfferResponse } from "../definitions/SaveOfferResponse";
import { AddPurchaseOrder } from "../definitions/AddPurchaseOrder";
import { AddPurchaseOrderResponse } from "../definitions/AddPurchaseOrderResponse";
import { SaveExpectedArrival } from "../definitions/SaveExpectedArrival";
import { SaveExpectedArrivalResponse } from "../definitions/SaveExpectedArrivalResponse";
import { CancelExpectedArrival } from "../definitions/CancelExpectedArrival";
import { CancelExpectedArrivalResponse } from "../definitions/CancelExpectedArrivalResponse";
import { CancelExpectedArrivalComponent } from "../definitions/CancelExpectedArrivalComponent";
import { CancelExpectedArrivalComponentResponse } from "../definitions/CancelExpectedArrivalComponentResponse";
import { GetOrderInfo } from "../definitions/GetOrderInfo";
import { GetOrderInfoResponse } from "../definitions/GetOrderInfoResponse";
import { GetOffers } from "../definitions/GetOffers";
import { GetOffersResponse } from "../definitions/GetOffersResponse";
import { AddMailer } from "../definitions/AddMailer";
import { AddMailerResponse } from "../definitions/AddMailerResponse";
import { AddPreRegisteredUser } from "../definitions/AddPreRegisteredUser";
import { AddPreRegisteredUserResponse } from "../definitions/AddPreRegisteredUserResponse";
import { GetDetailedBilling } from "../definitions/GetDetailedBilling";
import { GetDetailedBillingResponse } from "../definitions/GetDetailedBillingResponse";
import { GetProductShipmentAllProds } from "../definitions/GetProductShipmentAllProds";
import { GetProductShipmentAllProdsResponse } from "../definitions/GetProductShipmentAllProdsResponse";
import { GetProductShipmentProdList } from "../definitions/GetProductShipmentProdList";
import { GetProductShipmentProdListResponse } from "../definitions/GetProductShipmentProdListResponse";
import { GetShippingActivity } from "../definitions/GetShippingActivity";
import { GetShippingActivityResponse } from "../definitions/GetShippingActivityResponse";
import { GetProductReturns } from "../definitions/GetProductReturns";
import { GetProductReturnsResponse } from "../definitions/GetProductReturnsResponse";
import { GetProductSerialNumbers } from "../definitions/GetProductSerialNumbers";
import { GetProductSerialNumbersResponse } from "../definitions/GetProductSerialNumbersResponse";
import { GetShippingCharge } from "../definitions/GetShippingCharge";
import { GetShippingChargeResponse } from "../definitions/GetShippingChargeResponse";
import { AddOrder } from "../definitions/AddOrder";
import { AddOrderResponse } from "../definitions/AddOrderResponse";
import { AddSizeColorCluster } from "../definitions/AddSizeColorCluster";
import { AddSizeColorClusterResponse } from "../definitions/AddSizeColorClusterResponse";
import { AddProductListCluster } from "../definitions/AddProductListCluster";
import { AddProductListClusterResponse } from "../definitions/AddProductListClusterResponse";
import { CreateProductFromJson } from "../definitions/CreateProductFromJson";
import { CreateProductFromJsonResponse } from "../definitions/CreateProductFromJsonResponse";
import { CreateOfferFromJson } from "../definitions/CreateOfferFromJson";
import { CreateOfferFromJsonResponse } from "../definitions/CreateOfferFromJsonResponse";
import { CreateExpectedArrivalFromJson } from "../definitions/CreateExpectedArrivalFromJson";
import { CreateExpectedArrivalFromJsonResponse } from "../definitions/CreateExpectedArrivalFromJsonResponse";
import { CreatePurchaseOrderFromJson } from "../definitions/CreatePurchaseOrderFromJson";
import { CreatePurchaseOrderFromJsonResponse } from "../definitions/CreatePurchaseOrderFromJsonResponse";
import { CreateUserPreRegisteredFromJson } from "../definitions/CreateUserPreRegisteredFromJson";
import { CreateUserPreRegisteredFromJsonResponse } from "../definitions/CreateUserPreRegisteredFromJsonResponse";
import { CreateSizeColorClusterFromJson } from "../definitions/CreateSizeColorClusterFromJson";
import { CreateSizeColorClusterFromJsonResponse } from "../definitions/CreateSizeColorClusterFromJsonResponse";
import { CreateProductListClusterFromJson } from "../definitions/CreateProductListClusterFromJson";
import { CreateProductListClusterFromJsonResponse } from "../definitions/CreateProductListClusterFromJsonResponse";
import { GetProductAvailabilities } from "../definitions/GetProductAvailabilities";
import { GetProductAvailabilitiesResponse } from "../definitions/GetProductAvailabilitiesResponse";
import { GetProduct } from "../definitions/GetProduct";
import { GetProductResponse } from "../definitions/GetProductResponse";
import { GetExpectedArrivals } from "../definitions/GetExpectedArrivals";
import { GetExpectedArrivalsResponse } from "../definitions/GetExpectedArrivalsResponse";

export interface OrderSoap {
    AddProduct(addProduct: AddProduct, callback: (err: any, result: AddProductResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SaveOffer(saveOffer: SaveOffer, callback: (err: any, result: SaveOfferResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddPurchaseOrder(addPurchaseOrder: AddPurchaseOrder, callback: (err: any, result: AddPurchaseOrderResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SaveExpectedArrival(saveExpectedArrival: SaveExpectedArrival, callback: (err: any, result: SaveExpectedArrivalResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CancelExpectedArrival(cancelExpectedArrival: CancelExpectedArrival, callback: (err: any, result: CancelExpectedArrivalResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CancelExpectedArrivalComponent(cancelExpectedArrivalComponent: CancelExpectedArrivalComponent, callback: (err: any, result: CancelExpectedArrivalComponentResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOrderInfo(getOrderInfo: GetOrderInfo, callback: (err: any, result: GetOrderInfoResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetOffers(getOffers: GetOffers, callback: (err: any, result: GetOffersResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddMailer(addMailer: AddMailer, callback: (err: any, result: AddMailerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddPreRegisteredUser(addPreRegisteredUser: AddPreRegisteredUser, callback: (err: any, result: AddPreRegisteredUserResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetDetailedBilling(getDetailedBilling: GetDetailedBilling, callback: (err: any, result: GetDetailedBillingResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetProductShipmentAllProds(getProductShipmentAllProds: GetProductShipmentAllProds, callback: (err: any, result: GetProductShipmentAllProdsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetProductShipmentProdList(getProductShipmentProdList: GetProductShipmentProdList, callback: (err: any, result: GetProductShipmentProdListResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetShippingActivity(getShippingActivity: GetShippingActivity, callback: (err: any, result: GetShippingActivityResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetProductReturns(getProductReturns: GetProductReturns, callback: (err: any, result: GetProductReturnsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetProductSerialNumbers(getProductSerialNumbers: GetProductSerialNumbers, callback: (err: any, result: GetProductSerialNumbersResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetShippingCharge(getShippingCharge: GetShippingCharge, callback: (err: any, result: GetShippingChargeResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddOrder(addOrder: AddOrder, callback: (err: any, result: AddOrderResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddSizeColorCluster(addSizeColorCluster: AddSizeColorCluster, callback: (err: any, result: AddSizeColorClusterResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    AddProductListCluster(addProductListCluster: AddProductListCluster, callback: (err: any, result: AddProductListClusterResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateProductFromJSON(createProductFromJson: CreateProductFromJson, callback: (err: any, result: CreateProductFromJsonResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateOfferFromJSON(createOfferFromJson: CreateOfferFromJson, callback: (err: any, result: CreateOfferFromJsonResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateExpectedArrivalFromJSON(createExpectedArrivalFromJson: CreateExpectedArrivalFromJson, callback: (err: any, result: CreateExpectedArrivalFromJsonResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreatePurchaseOrderFromJSON(createPurchaseOrderFromJson: CreatePurchaseOrderFromJson, callback: (err: any, result: CreatePurchaseOrderFromJsonResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateUserPreRegisteredFromJSON(createUserPreRegisteredFromJson: CreateUserPreRegisteredFromJson, callback: (err: any, result: CreateUserPreRegisteredFromJsonResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateSizeColorClusterFromJSON(createSizeColorClusterFromJson: CreateSizeColorClusterFromJson, callback: (err: any, result: CreateSizeColorClusterFromJsonResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CreateProductListClusterFromJSON(createProductListClusterFromJson: CreateProductListClusterFromJson, callback: (err: any, result: CreateProductListClusterFromJsonResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetProductAvailabilities(getProductAvailabilities: GetProductAvailabilities, callback: (err: any, result: GetProductAvailabilitiesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetProduct(getProduct: GetProduct, callback: (err: any, result: GetProductResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetExpectedArrivals(getExpectedArrivals: GetExpectedArrivals, callback: (err: any, result: GetExpectedArrivalsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
